### ISSUE TITLE
Materialize forms.

### ISSUE THREAD

**Issue by ericjames3681** [ericjames3681/laughing-stock#1]
Able to provide text fields for strings of my venues/new, but i haven't been able to utilize a dropdown or checkbox for enum and booleans. 

https://materializecss.com/dropdown.html

https://www.tutorialspoint.com/materialize/materialize_form.html

https://www.youtube.com/watch?v=LlLjAuoCxsk&t=108s

**Comment by myDeveloperJourney** [comment]
During this meeting, we discovered that they Materialize form `select` widgets might better suited for what we were trying to do with form rather than using menu drop down widgets
